### ISSUE TITLE
Mouse Scroll 

### ISSUE THREAD

**Issue by mino-0** [ebicep/ChatPlus#10]
When I scroll with the mouse wheel, there is no change in the chat, but can I scroll with the mouse?

**Comment by ebicep** [comment]
Can you post 
1. Your Minecraft version with loader
2. Any other mods you are using, also please check if its still an issue when you only use ChatPlus
3. A video demonstration

**Comment by mino-0** [comment]
My minecraft version is 1.20.1 with fabric

When using chat plus, scrolling is not possible, but when chat plus is uneable, scrolling is possible.

https://github.com/ebicep/ChatPlus/assets/59308944/8a992263-2922-482c-ab39-f36dca0445b8

↓ Using mod
![image](https://github.com/ebicep/ChatPlus/assets/59308944/fd1c1919-df8b-4099-91a9-8bb2d9400356)

*1.0.1 version can scroll but Weird characters appear in chat.

1.1.0 version can't scroll

I deleted all modes and installed only chatplus and dependence, but scrolling did not work in version 1.1.0.

**Comment by mino-0** [comment]
Although it was not resolved in version 1.1.0, scrolling is available in version 1.0.1, so version 1.0.1 is used.
Thank you for making a good mod.

**Comment by ebicep** [comment]
Fixed in v1.1.1
