### ISSUE TITLE
[Feature change] Chat height after fullscreen/window resize 

### ISSUE THREAD

**Issue by IdaEdz** [ebicep/ChatPlus#14]
The problem:
I moved the chat up and across the screen. Then I  went out of full screen mode and later back to it.
I realized that the chat had been moved rather than scaled.

This made the chat now stand tall from bottom of the screen to the top.
With the keybind for resize the chat window I can make it wider and thinner, 
but my mouse cursor is not able to catch the top or bottom of the chat  window to make it shorter.

Making my chat window permanent height from top to bottom.

Potential solutions:
1. A button to reset the chat size settings.
2. Variable sliders to change the height/width
3. Scale the chat with window size changes.
4. Offset maximum chat height/width under maximum window height/width. To make the mouse able to grab the edges.

**Comment by ebicep** [comment]
Can you show a video of what you are talking about, the location of the chat before/after/the position you wanted, along with your mouse not being able to grab the edge.

**Comment by IdaEdz** [comment]
I'm sorry I tried it again and I can indeed drag the top edge. I'm just stupid.

I pressed my cursor all the way to the top of my screen as I thought that the chat border was there, but now when I lowered my cursor a couple of pixels I was able to grab the edge and then resize the chat window.
