### ISSUE TITLE
Chat tabs ??

### ISSUE THREAD

**Issue by meowisme** [ebicep/ChatPlus#15]
I got this mod mainly for the chat tabs... I play on a server so it'd be useful for me to have tabs to keep my messages more organized... but I'm quite lost on what to even do with them and there's no wiki to help.

What is the purpose of them ?

**Comment by ebicep** [comment]
https://github.com/ebicep/ChatPlus/wiki/Chat-Tabs

Leave any further questions you many have here, but if you are satisfied with the information provided please close this issue.

**Comment by walkersgaming** [comment]
> https://github.com/ebicep/ChatPlus/wiki/Chat-Tabs
> 
> Leave any further questions you many have here, but if you are satisfied with the information provided please close this issue.

Can multiple chat windows be created for different TABs? If not, can I request it?

**Comment by ebicep** [comment]
> > https://github.com/ebicep/ChatPlus/wiki/Chat-Tabs
> > Leave any further questions you many have here, but if you are satisfied with the information provided please close this issue.
> 
> Can multiple chat windows be created for different TABs? If not, can I request it?

Currently no but I'll see what I can do to implement it
