### ISSUE TITLE
Translation question

### ISSUE THREAD

**Issue by lynxaradev** [ebicep/ChatPlus#17]
I tried to find wiki, but didn't find any. How to make translations work for my specific scenario.
I have a friend that speaks only Russian, I need his messages to be translated to English, while all incoming messages to him into Russian
What does he need to do?

**Comment by ebicep** [comment]
New wiki page: https://github.com/ebicep/ChatPlus/wiki/Translator

In Config > Translator, his settings should look like
`Translate To` = Russian (incoming messages will be translated to Russian)
`Self Language` = Russian (he types in Russian)
`Speaking Language` = English (his messages will be translated to English)

Then whenever he wants to type in English then he can either use the `Translate Shortcut` to open the chat with the translator auto enabled OR when he has his chat open, he can click the bottom right corner which should have a box labelled `English`.

He also needs to add custom regexes to auto translate incoming messages or control click every single one. (See wiki for example)

**Comment by ebicep** [comment]
Closed due to inactivity. If you have more questions then reopen.
