### ISSUE TITLE
Chat modifications reset

### ISSUE THREAD

**Issue by baailey** [ebicep/ChatPlus#18]
Whenever I move my chat around or make it larger/smaller/wider, it will always reset to the default position the next time I open Minecraft. Is there an option I need to be enabling to have it preserve the changes I've made? Or is this a bug?

**Comment by baailey** [comment]
Sometimes it resets without me even leaving the server I'm on

**Comment by ebicep** [comment]
Seems like a bug can you try these things
1. See if it works just using ChatPlus alone (only have ChatPlus, resize, then restart)
2. Check the config (configs/ChatPlus/ChatPlus.json). See if the values change (x, y, width, height, try also testing other values). It might take 30s to update in real time but should update when you close mc
3. Change the config to something yourself then start mc and see if it reflects in game

**Comment by ebicep** [comment]
If possible could you also send a video of this happening

**Comment by baailey** [comment]
hi, few things:
1. yes, this issue still occurs with just ChatPlus (excluding dependencies)
2. checking once, the x and y has been modified after restarts. prior to restart I have it at x=282, y=442, after restart it changes to x=94, y=-14
3. having mc closed, setting x and y to the values I have mentioned already and starting mc up does not reflect the changes ingame, and instead sets it back to 94, -14

here is a recording of the step-by-step I've explained in this comment: https://youtu.be/85M2iqzvb4U
when trying to demonstrate this bug to you I wasn't able to recreate the actual width/height being modified, but I can 1000% confirm that there have been times I've moved the height down to closely mimic default mc size, and then it resets to go to the top of the mc client window lol

**Comment by ebicep** [comment]
Should be fixed in next upcoming release

**Comment by baailey** [comment]
wonderful, thank you

**Comment by ebicep** [comment]
Can you confirm your scenario is fixed in v1.1.4

**Comment by baailey** [comment]
sorry for the late response, on version 1.1.4 the chat position is still resetting to a default value.

**Comment by ebicep** [comment]
It seems like when I reworked the handling the chat position I forgot to also update the logic to auto detect if the position is wrong (fixed in next release). To confirm, can you manually update the position by resizing your game (make window smaller then back) and see if the chat goes back to its correct position?

**Comment by baailey** [comment]
i can confirm the chat position remains in the location I have moved it to even after resizing the game window manually

**Comment by ebicep** [comment]
Can you confirm this is fixed in v2.0.0

**Comment by baailey** [comment]
all good, thanks
