### ISSUE TITLE
Config is using system-specific paths

### ISSUE THREAD

**Issue by Pablete1234** [ebicep/ChatPlus#21]
At the moment the config is stored in `.minecraft / config\chatplus / chatplus.json` in linux systems. 

If you're using any hardcoded `\` please change them to `File.separator` instead.
https://github.com/ebicep/ChatPlus/blob/version/1.21/common/src/main/kotlin/com/ebicep/chatplus/config/Config.kt#L40 seems to be one of the offenders

**Comment by ebicep** [comment]
Should be fixed in the next release through the use of / instead.

**Comment by ebicep** [comment]
Can you confirm this is fixed in v2.0.0

**Comment by Pablete1234** [comment]
Seems to be fixed in v2
