### ISSUE TITLE
Paddings need some work

### ISSUE THREAD

**Issue by Pablete1234** [ebicep/ChatPlus#24]
- The messages start at the very very edge on the left, this is both ugly and makes text a bit harder to read
   - This space is in vanilla utilized for the scrollbar, which seems to be inexistent in chat plus (see #22 )
 - There is also a small padding for the textbox in vanilla that does not exist in chat plus, and that makes text feel totally squished down to the very bottom of the screen
 - When a chat message is continued in the next line, it has a bit of added indentation which makes it easier to follow

Chat plus vs vanilla-like (using advanced chat here, but using vanilla's chat):
![image](https://github.com/user-attachments/assets/dd6b2192-8508-4acc-adbb-7a039eb4bf99)

![image](https://github.com/user-attachments/assets/5e67fbc7-9a89-4084-9bd6-a23b905a5aa2)

**Comment by ebicep** [comment]
> The messages start at the very very edge on the left, this is both ugly and makes text a bit harder to read
> * This space is in vanilla utilized for the scrollbar, which seems to be inexistent in chat plus (see [Scrollbar does not render #22](https://github.com/ebicep/ChatPlus/issues/22) )

Custom padding will be added in the next release. 
I am also not sure what you mean by "edge on the left" and then "scrollbar" when the scroll bar is on the right.

> * There is also a small padding for the textbox in vanilla that does not exist in chat plus, and that makes text feel totally squished down to the very bottom of the screen

Additional configuration options for the input box will be added in the next release.

> * When a chat message is continued in the next line, it has a bit of added indentation which makes it easier to follow

I removed that indent because sometimes the indented line would overflow but I will readd it as a config option.

**Comment by Pablete1234** [comment]
> I am also not sure what you mean by "edge on the left" and then "scrollbar" when the scroll bar is on the right.

![image](https://github.com/user-attachments/assets/f7b046bf-0723-4ae0-acc8-3f1c18b2e278)

In vanilla the scrollbar is on the left

**Comment by ebicep** [comment]
> > I am also not sure what you mean by "edge on the left" and then "scrollbar" when the scroll bar is on the right.
> 
> ![image](https://private-user-images.githubusercontent.com/11789291/361190239-f7b046bf-0723-4ae0-acc8-3f1c18b2e278.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1OTcyMzMsIm5iZiI6MTcyNDU5NjkzMywicGF0aCI6Ii8xMTc4OTI5MS8zNjExOTAyMzktZjdiMDQ2YmYtMDcyMy00YWUwLWFjYzgtM2YxYzE4YjJlMjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDE0NDIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MWQ2NTc4MWEwMDhhMmY5ZWU3MTkzNDQ1MDcwNWE4NjM4Y2ViMzBlNTg4MWVjZGU3ZTcxOGU3ZGI3OTNlYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i1OiyrIQa_4UyPt4f4e7ivvvB9PnNiC8UFU_anutPXE)
> 
> In vanilla the scrollbar is on the left


I believe your image shows another modded chat. The vanilla chat has the "Server message. Cannot be reported" bar on the **left** and the scroll bar on the **right**
![image](https://github.com/user-attachments/assets/c5ed77e5-49f8-49ae-83a6-e66bc7f59367)

**Comment by Pablete1234** [comment]
It was from 1.18 from before the chat message verification changes in 1.19, so i guess that explains the difference

**Comment by ebicep** [comment]
Added in v2.0.0

**Comment by Pablete1234** [comment]
bottom padding = 0 (default) has some weird side effect

Chat focused
![image](https://github.com/user-attachments/assets/e19971bf-37c3-467d-9ffa-061bce0eb186)

Chat unfocused
![image](https://github.com/user-attachments/assets/e090174f-4c05-4615-a422-12ba89ceb041)

Changing it to 1 seems to mostly work-around/fix the issue, as the bottom-most text now has a background
it's still annoying that this causes the scrollbar to go 1px too low

With bottom padding = 1:
Chat focused:
![image](https://github.com/user-attachments/assets/8e47ed31-809b-4a9a-b0bd-ebf55b9e0a37)
Chat unfocused:
![image](https://github.com/user-attachments/assets/9541e59e-f647-444d-a4aa-5e5d3fdcc4ac)

To exaggerate the effect, padding =10:
Chat focused:
![image](https://github.com/user-attachments/assets/75a307fe-5137-4de7-a437-ebf33f262eb7)
Chat unfocused:
![image](https://github.com/user-attachments/assets/8b87033a-2b2b-4670-8d97-f343844b7b14)

Note that the padding is respected when unfocused, but not when focused, which is what leads to the scrollbar looking odd/out of place. I guess the better behavior here would be if when focused that padding was also back-filled

**Comment by ebicep** [comment]
Unable to reproduce
![image](https://github.com/user-attachments/assets/8a08f85b-0204-4872-91d7-f95d1aa23d2a)
Can you send your config file

**Comment by Pablete1234** [comment]
[chatplus-v2.json](https://github.com/user-attachments/files/16900455/chatplus-v2.json)

**Comment by ebicep** [comment]
Still unable to reproduce, tested on 1.20.2 and 1.21.
What version are you on + did you test it without using any other mods?
![image](https://github.com/user-attachments/assets/67821699-59cc-4ff0-9ec8-6eec1570d81f)

**Comment by Pablete1234** [comment]
I tested adding/removing mods until i found it, seems to be an incompatibility with ImmediatelyFast (https://github.com/RaphiMC/ImmediatelyFast)

**Comment by ebicep** [comment]
Still cant reproduce using ChatPlus 1.20.2/1.21 and ImmediatelyFast v1.2.21

![image](https://github.com/user-attachments/assets/ad5f75e5-ad2f-4ce5-b505-a026718b489c)

![image](https://github.com/user-attachments/assets/e59c6ca5-e739-4ad1-a3b8-bc3c3b1c7754)

**Comment by Pablete1234** [comment]
Seems like updating immediately fast from v1.2.20 to v1.2.21 fixed it
