### ISSUE TITLE
Focused and unfocused have different backgrounds without setting

### ISSUE THREAD

**Issue by Pablete1234** [ebicep/ChatPlus#25]
There seems to be no setting to have the same background opacity when chat is open or closed, leading to either too dark when open, or too light to read clearly when closed.

Consider either making the two adjustable separately or having a setting for how much darker/lighter it should be when open/closed so that it can  be configured as 0% darker/lighter and have them be the same color.

**Comment by ebicep** [comment]
Not sure what you mean by "Focused and unfocused have different backgrounds without setting/no setting to have the same background opacity when chat is open or closed", can you supply a screenshot? The background opacity should be the same if the chat is focused or not (tested).

**Comment by Pablete1234** [comment]
Unfocused chat:
![image](https://github.com/user-attachments/assets/410444dd-259d-4f62-877e-efbaaa726e58)

Focused chat:
![image](https://github.com/user-attachments/assets/bea437fe-6934-4faa-b8c8-ca2ce03fd0db)

Against  the same sky, one ends up having a color of #2E3E5C while the other is #4D6899

**Comment by ebicep** [comment]
Can you confirm this is fixed/not a problem in v2.0.0

**Comment by Pablete1234** [comment]
Can confirm this is solved
