### ISSUE TITLE
Chat window hides suggested commands

### ISSUE THREAD

**Issue by baailey** [ebicep/ChatPlus#27]
without chat being in the way: https://imgur.com/yg7RLkc
with chat in the way: https://i.imgur.com/UqLai69.png

when testing this it seems the actual chat messages are what hide it. if there are no messages, command suggestions appear fine

**Comment by Pablete1234** [comment]
This happens when tabs are enabled too, the  suggestions render *under* the tabs (note that time `set` is not visible at all):

![image](https://github.com/user-attachments/assets/ef51228f-f599-41f9-8981-a41a95a6aa0a)

**Comment by ebicep** [comment]
Fixed in v2.0.1, there maybe other overlapping rendering problems, please report them!
