### ISSUE TITLE
A bunch of bugs

### ISSUE THREAD

**Issue by FortiethSwing61** [ebicep/ChatPlus#3]
1. Most of the chat settings from Minecraft does not work
2. People's messages aren't being translated
3. Compact Chat doesn't always work
4. The mod 'Symbol Chat' isn't showing its functionalities in the chat screen (the mod's function in the screenshot are at the sign screen)
5. Sleeping on the bed softlocks the game, no leave bed button and pressing escape does nothing
![Polish_20240524_222025095](https://github.com/ebicep/ChatPlus/assets/91307287/b079e109-b94b-471f-9194-b944f9478a1c)
![2024-05-24_22 14 16](https://github.com/ebicep/ChatPlus/assets/91307287/04e7ce23-7f0b-4b82-8b5a-0235f1ac501b)

**Comment by ebicep** [comment]
1. Can you elaborate on what those settings are? Are you aware of the config options (/chatplus)? ChatPlus uses its own separate defined chat settings.
2. Can you elaborate on this also? Did you try control clicking? Do you have the proper language set in the config (Translate To)? Did you also know you need to set up custom translate regexes, the mod won't try to translate every message.
3. Can you show an example of this, hovering over both messages that should be compacted but aren't. It is probably the case that the messages look identical but their lore is different, most likely the timestamp if you have that enabled.
4. Based on how ChatPlus is implemented, overriding the vanilla chat screen with a clone one, most chat mods that use mixins on the vanilla chat screen will probably be incompatible, I'll try to look into this.
5. This will be fixed in the next update.

**Comment by FortiethSwing61** [comment]
1. I get that most of those has its own setting in your mod but the two setting that does not work and isn't on your mod are the width and focused height sliders
2. I do, so the mod doesn't automatically translate messages?
3. I already disabled the timestamps, the red text did got compact but the white ones did not, they have lores but they all exactly the same 
![Polish_20240525_093742835](https://github.com/ebicep/ChatPlus/assets/91307287/647b2dde-be99-4c1c-9f31-d8ca3fa94acb)
![Polish_20240525_093721298](https://github.com/ebicep/ChatPlus/assets/91307287/723a52ba-aec3-4786-8615-becc30820bb5)
4. I used another chat mod (Chat Patches) but they do appear and I don't have any issues with it
(Also, another feature from another mod (Bedrockify) that changes the chat's unfocused height position does not work)
5. O.O  okay

**Comment by ebicep** [comment]
1. You can actually change the height/width to whatever you want. In the config > Chat Key Binds > Move/Rescale Chat. You can move the chat box while holding that key on it, and you can change the height/width by holding that key and the corners of the box at the same time. Like shown in the picture (I am holding right control and clicking on the top right of the chat box).
![image](https://github.com/ebicep/ChatPlus/assets/34175525/8fe31c14-c18f-4e4e-9cda-e681266cd52f)
![image](https://github.com/ebicep/ChatPlus/assets/34175525/90510f1e-68fe-4a31-93ff-646147bc0ccd)

3. I'm not sure what you are referring to when you say "I do" (proper language set?). There is two ways of translating messages, manually by control clicking on the message or setting custom regexes like `\[.*?\] (\w{0,}: )` with the group index indicating the player's name which would be = 0 in this case. This is to prevent mass amounts of translation calls, especially if the message was from the server and not actual players.
![image](https://github.com/ebicep/ChatPlus/assets/34175525/aeeb1c91-58e2-4c30-94d1-b6ea938d821a)
![image](https://github.com/ebicep/ChatPlus/assets/34175525/2d9cf869-59c9-4a02-93cd-b4386d496a1e)

4. As of now, only **consecutive** messages get compacted.

5. You can change unfocused height in the config.
![image](https://github.com/ebicep/ChatPlus/assets/34175525/275fbab9-a8cb-40b8-810f-ad71c0e68e3f)

**Comment by FortiethSwing61** [comment]
1. Ohhhh, I get it now, mb
2. The "I do" was for setting 'Translate To', 'Speaking Language' and 'Self Language'  >.<
Weird question, where can I get a guide on those regex patterns? I know nothing about those, guess I'll just stick to clicking on the messages  ):

**Comment by ebicep** [comment]
Google "regex tester" or "regex guide". A nice one with a cheat sheet on the side is [https://regexr.com/](https://regexr.com/)

**Comment by ebicep** [comment]
4. Fixed in v1.1.0
5. Fixed in v1.1.0
