### ISSUE TITLE
Still Incompatible

### ISSUE THREAD

**Issue by AlphaLeoli** [ebicep/ChatPlus#31]
it's still incompatible with chat logs. it just won't let me open them if i have the mod enabled while im getting the chat messages.

**Comment by ebicep** [comment]
What version of ChatPlus/Minecraft/Launcher/chat logs are you on?

**Comment by AlphaLeoli** [comment]
**Minecraft:** 1.21
**Chat Logs:** 0.2.3
**Chat Plus:** 2.0.1

**Comment by ebicep** [comment]
Can you confirm this is fixed in v2.0.2?
I confirm tested for 1.20.1-1.20.6 but permanent chat logs just doesn't work for me on 1.21 even when using vanilla fabric with no other mods.

**Comment by AlphaLeoli** [comment]
yes it seems to be working rn thx
