### ISSUE TITLE
Suggestion: only compact same object data

### ISSUE THREAD

**Issue by AlphaLeoli** [ebicep/ChatPlus#35]
Just a toggle for this. That way, things like chat messages with clickable text won't stack if they are the same text with diff click events. But only if u want them to yk

**Comment by ebicep** [comment]
I am fairly certain the current method of compacting messages takes into account differing click events. Do you want a toggle this off?

**Comment by AlphaLeoli** [comment]
Yes a toggle for it

**Comment by ebicep** [comment]
Added in v2.1.0
