### ISSUE TITLE
Bug: Tab 'Skip Others' option not working

### ISSUE THREAD

**Issue by walkersgaming** [ebicep/ChatPlus#36]
I have custom regex on an additional tab and have checked 'Skip Others' but the messages filtered by regex into the 2nd tab, still appear in the main tab with the default select all regex

**Comment by ebicep** [comment]
Make sure the tab with 'Skip Others' has a higher priority than the 2nd tab, if you still have this problem please send your config and MC/launcher version.

**Comment by walkersgaming** [comment]
Oh, okay. You're right. However, I was hoping to have it apply across different chat windows. Is that possible?

**Comment by ebicep** [comment]
Fixed in v2.1.0

**Comment by walkersgaming** [comment]
Thanks for the quick fix! It works great when the higher priority window is first in the config. However, sometimes when I change the settings, it changes the order of my windows in the config, which appears to break the Skip Others functionality across windows.
