### ISSUE TITLE
Turn off chat auto-hiding.

### ISSUE THREAD

**Issue by IAMSolaara** [ebicep/ChatPlus#38]
Hi, I've been using this mod for the past few days and I love it!

I mostly played MMORPGs and always felt minecraft's chat to be severely lacking and basic and this pretty much fixes all of that.

One thing I do miss though is the ability to make chat show up all the time (or stop it from auto-hiding) so I can keep an eye on messages all the time, but I can't seem to find it in the options menu.

Is this going to be implemented? Maybe someone is already working on it? If not I could try and give it a shot myself if I can find the spare time ^^

**Comment by ebicep** [comment]
Added in v2.1.0 in Hide Chat section
