### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by OceC1apz** [ebicep/ChatPlus#39]
Every time trying to start a game on lunar client with this it crashes as i press /
![image_2024-09-27_180043413](https://github.com/user-attachments/assets/19523f61-bb65-41fa-9a3d-f175b292a433)

Will this ever be supported by lunar? If so when

**Comment by ebicep** [comment]
Can you post your crash log and loader/mc version

**Comment by OceC1apz** [comment]
My Mc version is 1.20.6    Crash ID: LCCR-55bba916ee1348338f64b5af24000ccc

**Comment by OceC1apz** [comment]
Should i try another version?

**Comment by ebicep** [comment]
I need the actual crash text file

**Comment by OceC1apz** [comment]
Honestly im not to sure of how to as i am not too advanced in terms of this, if you could help it would be amazing

**Comment by OceC1apz** [comment]
I just tried to also use verison 2.0.2 of the mod and it still crashed

**Comment by ebicep** [comment]
> Honestly im not to sure of how to as i am not too advanced in terms of this, if you could help it would be amazing 
> 
1. Crash your game
2. The logs should be at
C:\Users\PC1\.lunarclient\offline\files
3. Upload the file called latest.txt

**Comment by OceC1apz** [comment]
alright ill give that a go does that work?

[latest.log](https://github.com/user-attachments/files/17174405/latest.log)

**Comment by ebicep** [comment]
The issue is being investigated, so don't use either ChatPlus or Lunar for now.

**Comment by OceC1apz** [comment]
Any updates?

**Comment by ebicep** [comment]
Fixed in v2.1.1, there can be some issues with getting kicked/crashing. In the short time I tested was due to timestamps so disabling that may fix any problems you could have. (It is not fixable by me because lunar uses custom classes/internals/whatever)
