### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by FortiethSwing61** [ebicep/ChatPlus#4]
Can you add a feature that starts the chat from the top then all the way to the bottom?

**Comment by HyperPaint** [comment]
It's client-side functional, it can't be implemented in server-side
And this is a useless functionality, because everybody used to regular chat
Can you close issue? @ebicep

**Comment by FortiethSwing61** [comment]
Awww okay

**Comment by ebicep** [comment]
This is a client side mod and can still be done.

**Comment by HyperPaint** [comment]
It looks like I wrong with repository because the mods are named the same

https://modrinth.com/mod/chatplus

Sorry for the activity I caused here

**Comment by ebicep** [comment]
Added in v1.1.1
