### ISSUE TITLE
Config reordering windows order and breaking 'Skip Others'

### ISSUE THREAD

**Issue by walkersgaming** [ebicep/ChatPlus#40]
Thanks for the quick fix! It works great when the higher priority window is first in the config. However, sometimes when I change the settings, it changes the order of my windows in the config, which appears to break the Skip Others functionality across windows.

_Originally posted by @walkersgaming in https://github.com/ebicep/ChatPlus/issues/36#issuecomment-2373717013_

**Comment by ebicep** [comment]
Yes I saw and fixed but its just tedious to release 15 different versions but I'll get to it soon

**Comment by ebicep** [comment]
Fixed in v2.1.1
