### ISSUE TITLE
Chat window width incredibly small

### ISSUE THREAD

**Issue by AeonMC** [ebicep/ChatPlus#43]
With mod enabled:
![javaw_u1xuGBS3P2](https://github.com/user-attachments/assets/ed5d9d87-fb4a-44d5-9327-97ddde31c59d)

With mod disabled:
![javaw_FOxk2Hvt8U](https://github.com/user-attachments/assets/654ec149-a180-47c6-a506-6cd63fd22055)

Using Fabric 1.21, with out of the box Chat Plus 2.1.1

**Comment by ebicep** [comment]
You can rescale the chat to your liking, see the Rescale Chat key bind in the config, hover over the option for more information.

**Comment by AeonMC** [comment]
Thanks for the quick reply, the scaling feature definitely works!

A little suggestion for a future update: add some sort of indication that you can resize because right now it's relatively hidden and you have to know to click and drag the edges to extend it. Loving your mod so far, thanks for your work!❤
