### ISSUE TITLE
Automated tabs

### ISSUE THREAD

**Issue by Darkagia2** [ebicep/ChatPlus#45]
One of the huge features I have been looking for is tab automation. I see its possible to create tabs for keeping private messages going but would it be possible for any incoming /msg messages to be sent to their own tab and create a prefix to respond to the person sending the message?

On busy servers I feel like this would help to organize messages and make sure nothing is missed due to server spam.

**Comment by ebicep** [comment]
Added in v2.2.0. See [Wiki](https://github.com/ebicep/ChatPlus/wiki/Chat-Tabs#auto-tab-creator) for more info.

**Comment by Darkagia2** [comment]
Thanks Ebicep! Now I have to get smart enough to understand how to set up the settings lol
