### ISSUE TITLE
"Problem" with version

### ISSUE THREAD

**Issue by Limusssss** [ebicep/ChatPlus#46]
Its not exactly bug or something like that. Im curious is there plan to make version of mod for minecraft 1,21/1.21.1? I mean, in perspective of next month? How long is chance, we gonna wait?

**Comment by ebicep** [comment]
Not sure what you mean, there already is a 1.21 version?

**Comment by Limusssss** [comment]
Yeah, but also for forge? I mean,  on modrinth was only neoforge and fabric.

**Comment by ebicep** [comment]
I was not aware forge finally caught up, will hopefully add within the week.

**Comment by ebicep** [comment]
I now remember the actual reason I didn't update before, this mod depends on Architectury API which has not been updated to forge 1.21, and they are not planning to update I believe. If they ever do then I will also update.
