### ISSUE TITLE
Configuring max messages is impossible via ui

### ISSUE THREAD

**Issue by Pablete1234** [ebicep/ChatPlus#49]
The ui has a slider for max messages to keep, but the size is completely absurd. The minimum is 1000, but moving it even a single pixel to the right causes that minimum to jump to 95330. It's impossible to set a sensible amount (eg: 10k or 50k)

![image](https://github.com/user-attachments/assets/0236fce3-ce29-4017-9329-95e9fb618adc)

Minecraft 1.21.1, chat plus 2.1.0

**Comment by ebicep** [comment]
Added in v2.2.0, you can now just input whatever number you want.
