### ISSUE TITLE
Chat size not default Minecraft size on fresh install.

### ISSUE THREAD

**Issue by StoneLegion** [ebicep/ChatPlus#50]
### Describe your issue

I was thinking of adding this into a Pack I'm working on. We use to use tabbychat a lot. I noticed the window size was really tinny about 4 times smaller horizontal wise. 

I assume this is not intended but thought I mention it. I will take a look again in the future, I kind of like to see it mimic most of vanilla MC to start with then let people adjust it like crazy.

### MC/Loader/ChatPlus Version

neoforge 21.1.66 and chatplus 2.1.1

**Comment by ebicep** [comment]
You can rescale the chat, see the key bind in the config.
