### ISSUE TITLE
Vanilla Z Positions are not the same

### ISSUE THREAD

**Issue by AlphaLeoli** [ebicep/ChatPlus#51]
### Describe your issue

The z position is not the same as it is in vanilla. This is different from the x and y positions, which are changed by moving the chat (though this shouldn't affect the z position, since that's how close it is to the camera). This means that it would make compatibility with some things not really work, like with bleach hack.

### MC/Loader/ChatPlus Version

Chat Plus: 2.1.0
Minecraft: 1.21.1

### If applicable, add screenshots to help explain your problem.

![{4B532F51-7D95-4495-B4A1-ADACB9E83032}](https://github.com/user-attachments/assets/6b227cdc-36f1-4e07-b655-37012ae6cdd3)
These are for TEXT SHADOWS not the actual text. as you can see, the cp ones are different than the vanilla ones. For context, this is my glsl for a texture pack in making

**Comment by ebicep** [comment]
What exactly do you want? For the z value to match vanilla (50? from your screenshot)? There are a lot of things rendered for ChatPlus that changing any z value would mean scaling every other z. I could also just make the z values customizable in the config.

**Comment by AlphaLeoli** [comment]
i mean i guess it might be fine.. as long as they don't interfere with other vanilla. it would mean more work for other people who want to add compatibility, but i dont know if that's anything common it might just mean more work for you. so i suppose it's fine

**Comment by ebicep** [comment]
Still not sure what exactly you want and this seems to be a non issue for now. If you run into any issues though you can reopen this.
