### ISSUE TITLE
Movable blocks message components with custom click event

### ISSUE THREAD

**Issue by andriihorpenko** [ebicep/ChatPlus#52]
### Describe your issue

When the "Movable chat" is enabled, chat components with click event are ignored as movable handler has higher priority.
To reproduce, send a message with a click event into the chat, enable "Movable" and try clicking on the component.

### MC/Loader/ChatPlus Version

Minecraft 1.20.1, Forge 47.3.10, ChatPlus 2.2.0

**Comment by ebicep** [comment]
That is intended as if you were to try and move the chat box but click on a message, it might open your chat or do something else which prevents you from moving the chat.

**Comment by andriihorpenko** [comment]
What do you think about adding a handle to the corner of the chat box? This way you can preserve both intuitive visual indicator for the movable, and also save click actions?

**Comment by ebicep** [comment]
Is there a reason why you can't just toggle movable chat off, then on when you need it? The assumption is that once you move your chat, you wouldn't need move it again/for a while and the toggle prevents accidental moving. It's intuitive to resize your chat using the edges and move it by drag clicking the center, not sure what you mean by have an indicator at the corner.

**Comment by andriihorpenko** [comment]
I get your point, sure that will work, just a bit counterintuitive to me as there is no indication or cursor change when hovering over edges, I accidentally found out I could scale the chat box.
Regarding indicators: take a look what TabbyChat 2 (a chat mod for 1.12.2) has:
<img width="300" alt="image" src="https://github.com/user-attachments/assets/69384722-acdf-4e8e-8159-b0f894ccbd13">
The first icon is a handle to move the window, and the second is a handle to scale the window.

**Comment by ebicep** [comment]
Better indications was planned, I just forgot about them, will hopefully be added next release.

**Comment by ebicep** [comment]
Added in v2.3.0
