### ISSUE TITLE
Player heads are rendered incorrectly

### ISSUE THREAD

**Issue by andriihorpenko** [ebicep/ChatPlus#53]
### Describe your issue

This is how a head looks like in player tab:
<img width="150" alt="Screenshot 2024-10-23 at 23 02 59" src="https://github.com/user-attachments/assets/fdda4f9b-e03e-469d-bfcf-08af69929907">

And this is how it looks like in ChatPlus:
<img width="100" alt="image" src="https://github.com/user-attachments/assets/71b6c39a-16a4-4493-af11-e694cea37b20">

### MC/Loader/ChatPlus Version

Minecraft 1.20.1, Forge 47.3.10, ChatPlus 2.2.0

**Comment by andriihorpenko** [comment]
Looks like you're always rendering hat model part, when it should be conditional, just like in the player tab.

**Comment by ebicep** [comment]
Not sure what you mean by conditional, but a toggle will at least be added for the hat.

**Comment by ebicep** [comment]
Fixed in v2.3.0
