### ISSUE TITLE
Notification badges appear under outline

### ISSUE THREAD

**Issue by andriihorpenko** [ebicep/ChatPlus#54]
### Describe your issue

With Outline Box Type set to "Text and Tab box", notification badges appear beneath the outline.

<img width="155" alt="image" src="https://github.com/user-attachments/assets/80d7dc5b-cf5b-417e-82d6-c264947e8f70">

Setting `PoseStack#guiForward` amount from `0` to `100` seems to fix the issue.
https://github.com/ebicep/ChatPlus/blob/c7802fee13f77a9a218cd0cebb930abddfe6d842/common/src/main/kotlin/com/ebicep/chatplus/features/chatwindows/TabSettings.kt#L239

### MC/Loader/ChatPlus Version

Minecraft 1.20.1, Forge 47.3.10, ChatPlus 2.2.0

**Comment by ebicep** [comment]
Fixed in v2.3.0
