### ISSUE TITLE
Auto Tab Creator ignores components with empty root

### ISSUE THREAD

**Issue by andriihorpenko** [ebicep/ChatPlus#55]
### Describe your issue

Suppose you receive the following component:
```kotlin
Component.empty().apply {
    append("Hello")
}
```

Auto Tab Creator will not match this component whatsoever because of the following check:
https://github.com/ebicep/ChatPlus/blob/c7802fee13f77a9a218cd0cebb930abddfe6d842/common/src/main/kotlin/com/ebicep/chatplus/features/chattabs/AutoTabCreator.kt#L49

Removing this check seems to fix the issue. Not sure why this check is there in the first place, maybe there was some reason.

### MC/Loader/ChatPlus Version

Minecraft 1.20.1, Forge 47.3.10, ChatPlus 2.2.0

**Comment by ebicep** [comment]
Fixed in v2.3.0
