### ISSUE TITLE
Auto chat tabs isn't possible for certain DM formats which don't conflict with other messages

### ISSUE THREAD

**Issue by Kladki** [ebicep/ChatPlus#58]
PvP Legacy uses the following format for direct messages:
- Outgoing: `[You -> $player] $message`  
- Incoming: `[$player -> You] $message`

Because of this, the only way to make the regular expression with a single group is something like this:
```
\[(You -> )?(\w+)( -> You)?\] .*
```

But this causes system messages like this to make their own tab:
```
[GameManager] foo
```

Feel free to correct me if I'm wrong.

**Comment by ebicep** [comment]
Added in v2.3.0 (Added Auto Tab Creator removing group indexes not found) [Solution in Wiki](https://github.com/ebicep/ChatPlus/wiki/Chat-Tabs#pvp-legacy-example)

**Comment by Kladki** [comment]
Thank you!
