### ISSUE TITLE
can't click links in-game

### ISSUE THREAD

**Issue by ladythei** [ebicep/ChatPlus#60]
### Describe your issue

chat plus doesn't allow me to click links. is there something i'm missing?

i'm an admin on an smp server, and part of my duties is to teleport to players who trigger our anti-cheat warnings. as well, our players usually post links to their live streams, and i like to check on those to make sure they're legitimate streams, not something dubious. usually, i can do by clicking the warning, but with chat plus active, i cannot. if this is really the case, and not some kind of setting i'm not activating, then i hope this project can be adjusted to allow links to work, as i really enjoy it otherwise. it just doesn't let me do my job

### MC/Loader/ChatPlus Version

chatplus-fabric-2.3.0
![Screenshot 2024-11-08 102653](https://github.com/user-attachments/assets/4c4888d5-0f88-4d30-8dc4-fb555a14acb4)

### If applicable, add screenshots to help explain your problem.

https://github.com/user-attachments/assets/4e059e9e-f57b-4b68-b022-7093e76bc1bf

**Comment by ebicep** [comment]
Turn off movable chat using the keybind found in the config.
