### ISSUE TITLE
Chat Width

### ISSUE THREAD

**Issue by SussyBob** [ebicep/ChatPlus#63]
### Describe your issue

Unable to set my chat width through the setting.

### MC/Loader/ChatPlus Version

1.21.1/Quilt/2.2.0

**Comment by ebicep** [comment]
Did you try toggling movable chat and then dragging the edge off the chat box?

**Comment by SussyBob** [comment]
it works, it's very unclear tho.. i think you should add that for the modrinth description, thanks a lot, i like your mod, ill star it, you can close this issue

**Comment by Kladki** [comment]
Might make sense to make the default chat size the same as vanilla tbh, since I have seen many issues about this. It certainly confused me at first.
