### ISSUE TITLE
Question/Suggestion - 1.21.3 version

### ISSUE THREAD

**Issue by GlitchOnDiscord** [ebicep/ChatPlus#66]
Curious to know if there will be an official 1.21.3 version. I'd love to try out this mod, but the server I play on is running 1.21.3.

_I'm not familiar with GitHub, so apologies if this isn't the right place or if I've labelled this incorrectly._

**Comment by ebicep** [comment]
I believe the 1.21.2 version should work if there were no breaking changes, if the are then yes an official version will be added next update

**Comment by GlitchOnDiscord** [comment]
Not sure if I'm just in the wrong place, but I only see versions for 1.21.1 on both Github & Modrinth.

I will happily wait for the next update though, thank you.

**Comment by ebicep** [comment]
Does the 1.21.1 version not work on 1.21.3?

**Comment by GlitchOnDiscord** [comment]
I couldn't get it to work, no, maybe I'm just a little slow when It comes to this though

**Comment by ebicep** [comment]
The only thing you would need to do is just put it in your mods folder with the updated dependencies, but if it doesn't with then it's not compatible and you'll just need to wait for new version

**Comment by GlitchOnDiscord** [comment]
Any possible time frame on an update to ChatPlus?

**Comment by ebicep** [comment]
Sorry for the delay, new version is out, please report any new problems if seen.

**Comment by dark4rmymc** [comment]
I tested this on 1.21.4 and it works perfectly so far, could you mark it as compatible with 1.21.3-4 on Modrinth?
