### ISSUE TITLE
Dynmap chat not working with ChatPlus

### ISSUE THREAD

**Issue by HyperPaint** [ebicep/ChatPlus#9]
Hi, i found some incompatibility. When ChatPlus enabled on my fabric server, chat messages not sends to Dynmap (browser), but messages from Dynmap (browser) to game works good.

versions:
minecraft fabric 1.20.4
chat-plus 0.20.2-mc1.20.4
dynmap 3.7-SNAPSHOT

In logs there is no errors, warn or info.

Can you check, where problem can be?

**Comment by ebicep** [comment]
This is a client side mod.

**Comment by HyperPaint** [comment]
It looks like I wrong with repository because the mods are named the same

https://modrinth.com/mod/chatplus

Sorry for the activity I caused here
